services:
  powersync:
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    image: journeyapps/powersync-service:latest
    command: ["start", "-r", "unified"]
    volumes:
      - ./config/config.yaml:/config/config.yaml
    environment:
      POWERSYNC_CONFIG_PATH: /config/config.yaml
      POWERSYNC_PORT: ${POWERSYNC_PORT}
    ports:
      - "${POWERSYNC_PORT}:8080"

  postgres:
    image: postgres:latest
    restart: always
    environment:
      PGPORT: ${PG_DATABASE_PORT}
      POSTGRES_DB: ${PG_DATABASE_NAME}
      POSTGRES_USER: ${PG_DATABASE_USER}
      POSTGRES_PASSWORD: ${PG_DATABASE_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "${PG_DATABASE_PORT}:5432"
    command: ["postgres", "-c", "wal_level=logical"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_DATABASE_USER} -d ${PG_DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5


  coredns:
    image: coredns/coredns:latest
    container_name: coredns
    restart: unless-stopped
    volumes:
      - ./coredns/Corefile:/etc/coredns/Corefile
      - ./coredns/allowed_hosts:/etc/coredns/allowed_hosts.hosts
    ports:
      - "${COREDNS_PORT}:53/tcp"
      - "${COREDNS_PORT}:53/udp"
    command: -conf /etc/coredns/Corefile

  wireguard:
    image: lscr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=${WG_PUID}
      - PGID=${WG_PGID}
      - TZ=${WG_TZ}
      - SERVERURL=${WG_SERVERURL}
      - SERVERPORT=${WG_SERVERPORT}
      - PEERS=${WG_PEERS}
      - PEERDNS=${WG_PEERDNS}
      - INTERNAL_SUBNET=${WG_INTERNAL_SUBNET}
      - ALLOWEDIPS=${WG_ALLOWEDIPS}
    volumes:
      - ~/wireguard/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped


volumes:
  pg_data:

